CREATE TABLE medicos
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    crm           VARCHAR(32) NOT NULL,
    nome          VARCHAR(255) NOT NULL,
    especialidade VARCHAR(255) NOT NULL,
    CONSTRAINT pk_medicos PRIMARY KEY (id)
);

ALTER TABLE medicos
    ADD CONSTRAINT uk_medicos_numero_crm UNIQUE (crm);

CREATE INDEX idx_medicos_numero_crm ON medicos (crm);