CREATE TABLE pacientes
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cpf             VARCHAR(255),
    nome            VARCHAR(255),
    data_nascimento date,
    CONSTRAINT pk_pacientes PRIMARY KEY (id)
);