CREATE TABLE agendamentos
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    medico_id         BIGINT NOT NULL,
    paciente_id       BIGINT NOT NULL,
    data_agendamento  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_agendamentos PRIMARY KEY (id),
    CONSTRAINT fk_agendamentos_medico FOREIGN KEY (medico_id) REFERENCES medicos (id),
    CONSTRAINT fk_agendamentos_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes (id),
    CONSTRAINT uk_agendamentos_medico_data UNIQUE (medico_id, data_agendamento)
);