spring.application.name=ClinicaMedica

# Banco hospedado
spring.datasource.url=jdbc:postgresql://clinica:develop@home.brunorsch.dev.br:55432/clinicamedica

# Banco local
# spring.datasource.url=jdbc:postgresql://clinica:develop@localhost:55432/clinicamedica

server.port=8001