spring.application.name=ClinicaMedica

# Banco hospedado
spring.datasource.url=jdbc:postgresql://home.brunorsch.dev.br:55432/clinicamedica
spring.datasource.username=clinica
spring.datasource.password=develop

# Banco local
# spring.datasource.url=jdbc:postgresql://localhost:55432/clinicamedica
# spring.datasource.username=clinica
# spring.datasource.password=develop

server.port=8001
